### ISSUE TITLE
Styling Project creation Form 

### ISSUE THREAD

**Issue by Mikequint94** [Mikequint94/MakeAnything#16]
Project Creation page is pretty.  Modal pops up asking what to share, followed by main picture to upload.  Then you can add steps with a button click and finally publish when complete.

**Comment by Mikequint94** [comment]
I think its pretty much good enough for project and step creation.  What do you think?  @rkoeze

**Comment by rkoeze** [comment]
Yup. I'd suggest going back and giving the step description text a style, but it meets MVP.
