### ISSUE TITLE
Seed Data with pictures/videos in instructions

### ISSUE THREAD

**Issue by Mikequint94** [Mikequint94/MakeAnything#21]

**Comment by Mikequint94** [comment]
i still need more seeds but i do have seeds with pics/vids

**Comment by Mikequint94** [comment]
@rkoeze

**Comment by rkoeze** [comment]
This is great! Just seed more projects and I'll check it off.

**Comment by Mikequint94** [comment]
I have 9 right now.  is that enough?  I definitely want more in the future but don't have time to do today i don't think @rkoeze
