### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by Mikequint94** [Mikequint94/MakeAnything#26]

**Comment by Mikequint94** [comment]
I am hosting on Heroku! https://make-anything-app.herokuapp.com/  Is this an okay site name or should I try to pick another?  @rkoeze

**Comment by rkoeze** [comment]
The site name is great! 

If you could add the heroku link to your repo readme and wiki that'd be great. 

Also, it looks like you're serving up some images from Cloudinary over HTTP and getting some console errors as a result. There's a setting in Cloudinary that you can change so it uses HTTPS.
