### ISSUE TITLE
User Auth styling on Splash Page

### ISSUE THREAD

**Issue by Mikequint94** [Mikequint94/MakeAnything#3]
Create nice NavBar on Splash Page with signup, login, and demo login buttons

**Comment by Mikequint94** [comment]
@rkoeze

**Comment by rkoeze** [comment]
This is great! I'd like you to do a bit more styling on the sign up and login forms. For example, make sure the form itself is centered, make the buttons and inputs larger. Check out the form from Instructables for inspiration. They don't use a dropdown, but they're using a similar amount of space as you are. 

![screen shot 2017-09-20 at 2 11 29 pm](https://user-images.githubusercontent.com/7535628/30667834-af8ccee2-9e0d-11e7-862f-0f949c42784a.png)

Taken on https://www.instructables.com/account/login/

Once you style this a bit more I'm ok with checking it off.
