### ISSUE TITLE
Steps Frontend

### ISSUE THREAD

**Issue by Mikequint94** [Mikequint94/MakeAnything#32]
get steps to show up well in project show page

**Comment by Mikequint94** [comment]
Done!! haven't seeded for heroku yet.  Having issues because the project numbers are different on my local host vs heroku.  Is there a way to sync these? @rkoeze

**Comment by rkoeze** [comment]
I'll come find you and we can talk!

**Comment by Mikequint94** [comment]
great, got it all working out :) @rkoeze
